CREATE TABLE Person (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL,
    age int CHECK (age >= 18),
    email varchar(200) NOT NULL UNIQUE
);

insert into Person(name, age, email) values ('test1', 21, 'test1@mail.com');
insert into Person(name, age, email) values ('test2', 22, 'test2@mail.com');
insert into Person(name, age, email) values ('test3', 23, 'test3@mail.com');
insert into Person(name, age, email) values ('test4', 24, 'test4@mail.com');
insert into Person(name, age, email) values ('test5', 25, 'test5@mail.com');
insert into Person(name, age, email) values ('test6', 26, 'test6@mail.com');
insert into Person(name, age, email) values ('test7', 27, 'test7@mail.com');
insert into Person(name, age, email) values ('test8', 28, 'test8@mail.com');
insert into Person(name, age, email) values ('test9', 29, 'test9@mail.com');
insert into Person(name, age, email) values ('test10', 30, 'test10@mail.com');
